/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicodemo.view;

import com.nicodemo.controller.ItemsController;
import com.nicodemo.model.Item;
import com.nicodemo.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Nico
 */
public class AddItemDialog extends javax.swing.JDialog {

    private ItemsController itemsController;
    private Item item;
    private int prevStock;
    private boolean update;
    /**
     * Creates new form AddItemDialog
     */
    public AddItemDialog(java.awt.Frame parent, boolean modal, ItemsController itemsController, Item item) {
        super(parent, modal);
        this.itemsController = itemsController;
        initComponents();
        
        if(item == null){
            this.item = new Item();
            prevStock = 0;
        }
        else{
            this.item = item;
            jLabel_title.setText("Modificar Artículo");
            jButton_save.setText("Guardar");
            update = true;            
            jTextField_stock.setEditable(User.getCurrentUser().hasPermissionOrIsRoot(User.Permission.UpdateItemStock));
        }
        prevStock = this.item.getStock();
        jTextField_code.setText(this.item.getCode()); 
        jTextField_description.setText(this.item.getDescription());
        jTextField_cost.setText(String.valueOf(this.item.getCost())); 
        jTextField_price.setText(String.valueOf(this.item.getPrice())); 
        jTextField_stock.setText(String.valueOf(this.item.getStock())); 
    }
    
    private Item buildItem(){
        item.setCode(jTextField_code.getText());
        item.setDescription(jTextField_description.getText());
        item.setCost(Float.parseFloat(jTextField_cost.getText()));
        item.setPrice(Float.parseFloat(jTextField_price.getText()));
        item.setStock(Integer.parseInt(jTextField_stock.getText()));
        
        return item;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_description = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_cost = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_stock = new javax.swing.JTextField();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Descripción");

        jLabel2.setText("Código");

        jLabel_title.setText("Alta de Articulo");

        jLabel4.setText("Costo");

        jLabel5.setText("Precio");

        jButton_save.setText("Guardar y agregar otro");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jLabel6.setText("Stock");

        jTextField_stock.setToolTipText("");

        jButton_cancel.setText("Cancelar");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jButton_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_save)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_description)
                            .addComponent(jTextField_cost)
                            .addComponent(jTextField_price, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jTextField_stock)
                            .addComponent(jTextField_code)))
                    .addComponent(jLabel_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        try {
            Validate();
            itemsController.saveItem(buildItem(), prevStock);
            if(update)
                this.dispose();
            else
                item = new Item();            
            jTextField_code.setText("");
            jTextField_description.setText("");
            jTextField_cost.setText("");
            jTextField_price.setText("");
            jTextField_stock.setText("");
        } catch (Exception ex) {
            String msg = "";
            Throwable throwable = ex;
            while (throwable != null) {
                msg = msg + throwable.getMessage() + "\n";
                throwable = throwable.getCause();
            }
            JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField jTextField_code;
    private javax.swing.JTextField jTextField_cost;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_stock;
    // End of variables declaration//GEN-END:variables

    private void Validate() throws Exception {
     if(jTextField_code.getText().trim().isEmpty())
        throw new Exception("Debe indicar un código valido");
     if(jTextField_description.getText().trim().isEmpty())
         throw new Exception("Debe indicar una Descripción");
    }
}
