/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicodemo.view;

import com.nicodemo.model.CashBox;
import com.nicodemo.model.User;
import com.nicodemo.persistence.DAOs.CashBoxesDAO;
import com.nicodemo.persistence.DAOs.UsersDAO;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.JDatePicker;

/**
 *
 * @author Nico
 */
public class LastCashBoxesDialog extends javax.swing.JDialog {

    private UsersDAO usersDAO;
    private CashBoxesDAO cashBoxesDAO;

    /**
     * Creates new form LastCashBoxesDialog
     */
    public LastCashBoxesDialog(java.awt.Frame parent, boolean modal, UsersDAO usersDAO, CashBoxesDAO cashBoxesDAO) {
        super(parent, modal);
        initComponents();
        this.usersDAO = usersDAO;
        this.cashBoxesDAO = cashBoxesDAO;

        Calendar calendarSince = Calendar.getInstance();
        calendarSince.add(Calendar.DAY_OF_MONTH, -7);
        dateChooserCombo_since.setSelectedDate(calendarSince);
        dateChooserCombo_since.setMaxDate(Calendar.getInstance());
        dateChooserCombo_to.setSelectedDate(Calendar.getInstance());
        dateChooserCombo_to.setMaxDate(Calendar.getInstance());

        refreshCombos();
        jbutton_SearchActionPerformed(null);
    }

    private void refreshCombos() {
        jComboBox_users.removeAllItems();
        jComboBox_users.addItem(new User("<TODOS>"));
        usersDAO.getAll().forEach(u -> jComboBox_users.addItem(u));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooserCombo_since = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo_to = new datechooser.beans.DateChooserCombo();
        jComboBox_users = new javax.swing.JComboBox();
        jbutton_Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Últimas Cajas");

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        jComboBox_users.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbutton_Search.setText("Buscar");
        jbutton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateChooserCombo_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateChooserCombo_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_users, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jbutton_Search)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo_since, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo_to, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jComboBox_users))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_SearchActionPerformed
        List<CashBox> chasBoxes = cashBoxesDAO.getAllByDateAndUser(dateChooserCombo_since.getSelectedDate().getTime(),
                dateChooserCombo_to.getSelectedDate().getTime(),
                (User) jComboBox_users.getSelectedItem());
        DefaultTableModel dtm = new NoEditableTableModel();

        String header[];
        header = new String[]{"Apertura", "Cierre", "Usuario",
            "Inicial", "Vendido", "Fiado", "D. Pagadas", "Final",
            "Costos", "Ganancias" };

        dtm.setColumnIdentifiers(header);
        jTable1.setModel(dtm);

        chasBoxes.stream().forEach((c) -> {
            dtm.addRow(new Object[]{
                c.getStartDateTime().toString(),
                c.getEndDateTime().toString(),
                c.getUser().getName(),
                c.getStartAmount(),
                c.sold(),
                c.debited(),
                c.payments(),
                c.getEndAmount(),
                c.costs(),
                c.profit()
            });
        });
    }//GEN-LAST:event_jbutton_SearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo_since;
    private datechooser.beans.DateChooserCombo dateChooserCombo_to;
    private javax.swing.JComboBox jComboBox_users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbutton_Search;
    // End of variables declaration//GEN-END:variables
}
