/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicodemo.view;

import com.nicodemo.controller.ItemsController;
import com.nicodemo.model.Item;
import com.nicodemo.model.ItemBrand;
import com.nicodemo.model.ItemKind;
import com.nicodemo.model.User;
import com.nicodemo.persistence.exceptions.ElementNotFoundException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico
 */
public class SelectItemDialog extends javax.swing.JDialog {

    private ItemsController itemsController;

    /**
     * Creates new form SelectItemDialog
     */
    public SelectItemDialog(java.awt.Frame parent, boolean modal, ItemsController itemsController, String keyword) {
        super(parent, modal);
        initComponents();
        this.itemsController = itemsController;
        this.jTextField_seachText.setText(keyword);
        refreshItems();
    }

    private void refreshItems() {
        DefaultTableModel dtm = new NoEditableTableModel();

        String header[];
        if (User.getCurrentUser().hasPermissionOrIsRoot(User.Permission.SeeItemsCost)) {
            header = new String[]{"Código", "Descripción", "Costo",
                "Precio", "Stock", "Tipo", "Marca"};
        } else {
            header = new String[]{"Código", "Descripción",
                "Precio", "Stock", "Tipo", "Marca"};
        }

        dtm.setColumnIdentifiers(header);
        jTable1.setModel(dtm);
        List<Item> items = itemsController.search(jTextField_seachText.getText(), null, null);

        if (User.getCurrentUser().hasPermissionOrIsRoot(User.Permission.SeeItemsCost)) {
            items.stream().forEach((i) -> {
                dtm.addRow(new Object[]{i.getCode(), i.getDescription(), i.getCost(), i.getPrice(), i.getStock(),
                    i.getKind(), i.getBrand()
                });
            });
        } else {
            items.stream().forEach((i) -> {
                dtm.addRow(new Object[]{i.getCode(), i.getDescription(), i.getPrice(), i.getStock(),
                    i.getKind(), i.getBrand()
                });
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_seachText = new javax.swing.JTextField();
        jButton_searchItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_ok.setText("Aceptar");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField_seachText.setText("jTextField1");
        jTextField_seachText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_seachTextKeyReleased(evt);
            }
        });

        jButton_searchItem.setText("Buscar");
        jButton_searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ok))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField_seachText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_searchItem)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_seachText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_searchItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchItemActionPerformed
        refreshItems();
    }//GEN-LAST:event_jButton_searchItemActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        Item item = getSelectedItem();
        if (item != null) {
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir un Artículo de la lista");
        }
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jTextField_seachTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_seachTextKeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            refreshItems();
        }
       if(evt.getKeyCode() == KeyEvent.VK_DOWN){
           jTable1.requestFocus();
       }
    }//GEN-LAST:event_jTextField_seachTextKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton_okActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1KeyReleased

    public Item getSelectedItem() {
        Item item = null;
        int rowIndex = jTable1.getSelectedRow();
        if (rowIndex >= 0) {
            try {
                String code = jTable1.getModel().getValueAt(rowIndex, 0).toString();
                item = itemsController.getByCode(code);
            } catch (ElementNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        return item;
    }
    
    @Override
    protected JRootPane createRootPane() { 
        JRootPane rootPane = new JRootPane();
        KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
        Action actionListener = new AbstractAction() { 
          public void actionPerformed(ActionEvent actionEvent) { 
            jTable1.clearSelection();
            setVisible(false);
            dispose();
          } 
        } ;
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ESCAPE");
        rootPane.getActionMap().put("ESCAPE", actionListener);

        return rootPane;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ok;
    private javax.swing.JButton jButton_searchItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_seachText;
    // End of variables declaration//GEN-END:variables
}
