/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicodemo.view;

import com.nicodemo.controller.UsersController;
import com.nicodemo.model.User;
import com.nicodemo.persistence.exceptions.ElementNotFoundException;
import java.awt.Font;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico
 */
public class UsersPanel extends javax.swing.JPanel {

    private UsersController usersController;
    /**
     * Creates new form UsersPanel
     */
    public UsersPanel(UsersController usersController) {
        this.usersController = usersController;
        initComponents();
        reloadUsers();
    }
    
    private void reloadUsers(){
        DefaultTableModel dtm = new NoEditableTableModel();
        String header[] = new String[]{"ID", "Nombre", "Permisos"};
        dtm.setColumnIdentifiers(header);
        jTable1.setModel(dtm);

        List<User> users = this.usersController.getUsers();

        users.stream().forEach((user) -> {
            dtm.addRow(new Object[]{
                user.getId(),
                user.getName(),
                user.getPermissions().stream().map((p)->p.getDescription()).collect(Collectors.joining(", "))
            }); });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_updateClient = new javax.swing.JButton();
        jButton_addUser = new javax.swing.JButton();

        jLabel1.setText("Usuarios - Permisos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");

        jButton_updateClient.setText("Modificar");
        jButton_updateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateClientActionPerformed(evt);
            }
        });

        jButton_addUser.setText("+ Usuario");
        jButton_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_updateClient))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_addUser)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_updateClient)
                .addContainerGap())
        );

        jButton_addUser.getAccessibleContext().setAccessibleName("Add");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addUserActionPerformed
        AddUserDialog dialog = new AddUserDialog(null, true, null, usersController);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowDeactivated(java.awt.event.WindowEvent e) {
                reloadUsers();
            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_addUserActionPerformed

    private void jButton_updateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateClientActionPerformed
        User user = this.getSelectedUser();
        if(user != null){
        AddUserDialog dialog = new AddUserDialog(null, true, user, usersController);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowDeactivated(java.awt.event.WindowEvent e) {
                reloadUsers();
            }
        });
        dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton_updateClientActionPerformed

    private User getSelectedUser() {
        User user = null;
        int rowIndex = jTable1.getSelectedRow();
        if (rowIndex >= 0) {
            try {
                int id = Integer.parseInt(jTable1.getModel().getValueAt(rowIndex, 0).toString());
                user = usersController.getUsers().stream().filter((u)->u.getId() == id).findFirst().get();
            } catch (Exception  ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir un usuario de la lista");
        }
        return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addUser;
    private javax.swing.JButton jButton_updateClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
